### ISSUE TITLE
wxapp-adapter 0.1.6版本下，demo跑不起来，切换回0.1.4就没问题了

### ISSUE THREAD

**Issue by SevenElement** [JetLua/fish#2]
原因如下
"@iro/wechat-adapter": "0.1.4"
![image](https://user-images.githubusercontent.com/7270377/67462833-e0d0dd80-f672-11e9-98a9-188406a96a3e.png)
"@iro/wechat-adapter": "0.1.6"
![image](https://user-images.githubusercontent.com/7270377/67462994-2ab9c380-f673-11e9-9883-77daf92dc1bb.png)

希望作者可以有空，向下兼容下

**Comment by JetLua** [comment]
收到，感谢反馈。

**Comment by JetLua** [comment]
修复了：https://github.com/JetLua/wechat-adapter/commit/852fcbd343b025562133c5211d298d9811dd96f9
